/** @format */
import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/themes';
import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import { Header } from '@/components/header';
import SideBar from '@/components/sidebar';
import { Container } from '@/components/container';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<ClerkProvider appearance={{ baseTheme: dark }}>
			<html lang="en">
				<body>
					<ThemeProvider
						attribute="class"
						forcedTheme="dark"
						storageKey="vinyl-vault-theme">
						<Header />
						<div className="flex h-full">
							<SideBar />
							<Container>{children}</Container>
						</div>
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
